Bit-Quill/arrow

java/flight/flight-jdbc-driver/pom.xml

The dep.protobuf.version variable was used in this fork https://github.com/rafael-telles/arrow/tree/flight-jdbc-driver where it was referencing variables in the parent pom that does not exist in the official arrow fork of flight-sql-jdbc which this branch is based off of. This caused a build issue where dep.protobuf.version is not defined. Changing it to dep.protobuf-bom.version fixes the build issue

Changed dep.protobuf.version to dep.protobuf-bom.version

---

cpp/src/flightsql_odbc/flightsql-odbc/README.md

Non existent FlightSQL readme file
The initial version of FlightSQL readme file
N/A
N/A

apacheGH-30622: [GAC-45] Initial Version of FlightSQL Readme

---

cpp/src/arrow/flight/sql/odbc/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_connection.cc
cpp/src/arrow/flight/sql/odbc/tests/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc

Implement SQLAllocEnv and SQLAllocHandle for environment

Implement  SQLAllocHandle for environment 

---

cpp/cmake_modules/DefineOptions.cmake
cpp/src/arrow/flight/sql/odbc/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/flight_sql/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/decimal_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/timestamp_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/config/configuration.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_auth_method.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_connection.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_connection.h
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_connection_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/get_info_cache.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/get_info_cache.h
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/ui/add_property_window.h
cpp/src/arrow/flight/sql/odbc/flight_sql/system_dsn.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/system_trust_store.h
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/add_property_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/custom_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/dsn_configuration_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/window.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_connection.cc

Fix build failures, so files can be included in cmake lists
Fix build issues with config window, system trust store, and cache info, and unit test in `flightsql-odbc`
Tested locally
No

Fix rest of `flightsql-odbc` build issues 

---

cpp/src/arrow/flight/sql/odbc/odbc_api.cc

Fix build issue from static flight sql driver
Passing a static flight sql driver into the static shared pointer causes compilation error.  Changing to have the static shared pointer create the underlying referenced sql driver fixes the issue.

Fix build issue from static flight sql driver

---

cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/binary_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/string_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/address_info.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/json_converter_test.cc

Fix 6 build warnings that get treated as error during build. This unblocks build

Fix build warnings that get treated as error

---

cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/odbc_handle.h
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc

Change code within odbc_api.cc to use ExecuteWithDiagnostics static function to catch and log any diagnostic errors raised during code execution.
Remove unused variable for caught memory allocation exception in odbc_handle.h as resulting warning causes compilation issue.

Implement use of ExecuteWithDiagnostics

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h

Implementation of SQLGetDiagField.

Implement SQLGetDiagField

---

cpp/src/arrow/flight/sql/odbc/flight_sql/system_dsn.h
cpp/src/arrow/flight/sql/odbc/flight_sql/win_system_dsn.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.cc

DSN window implementation developed according to [driver guidelines spec](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function?view=sql-server-ver16#driver-guidelines)

DSN window implementation

---

cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/attribute_utils.h
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc

Updates for SQLGetDiagFieldW coming from comments to initial merged [PR](https://github.com/Bit-Quill/arrow/pull/33).
Addresses the following issues:
- Add statement and descriptor cases now so we don't forget.
- Use const std::string& to use copy by reference semantics to avoid copy.
- Change to use dsn value retrieved from connection for SQL_DIAG_SERVER_NAME
- Allow passing of diagInfoPtr if they just want the length
- For GetStringAttribute calls set isLengthInBytes to true for calls with SQLPOINTER and to false for calls with SQLWCHAR
- Return dummy values for unimplemented field types
Fixed bug in attribute_utils.h for GetAttributeSQLWCHAR to determine when truncation has been applied.

Updates for SQLGetDiagFieldW

---

cpp/src/arrow/flight/sql/odbc/flight_sql/address_info.h
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_driver.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/win_system_dsn.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/logger.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/utils.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/utils.cc

Enable logging and add new logs inside ODBC APIs. Also changed `include <arrow...` to `include "arrow...` to use `"`. The changes are small so I squished them into the same PR.

Enable logging and add new logs

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc

Implement ODBC API with debug logging

Implement ODBC API with debug logging

---

cpp/src/arrow/flight/sql/odbc/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/config/configuration.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_connection.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/config/configuration.h
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/ui/add_property_window.h
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/ui/custom_window.h
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/ui/window.h
cpp/src/arrow/flight/sql/odbc/flight_sql/system_dsn.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/system_dsn.h
cpp/src/arrow/flight/sql/odbc/flight_sql/system_trust_store.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/system_trust_store.h
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/add_property_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/custom_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/dsn_configuration_window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/ui/window.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/win_system_dsn.cc
cpp/src/arrow/flight/sql/odbc/odbc.def
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_connection.cc
cpp/src/arrow/flight/sql/odbc/tests/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc
cpp/src/arrow/flight/sql/odbc/tests/odbc_test_suite.cc

- Add unicode support for DSN-related APIs
- Let compiler add `W` at end of applicable ODBC API names
- Change `ConfigDSN` to `ConfigDSNW`

Unicode support for DSN ODBC APIs

---

cpp/src/arrow/flight/sql/odbc/flight_sql/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_driver.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/utils_test.cc

As per changes from https://github.com/apache/arrow/issues/46261, we need to initialize Kernel library explicitly to get the functions registered.
Same as #50 except I wanted to fix the branch names.

Initialize Kernel Library

---

cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_connection.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_info_test.cc

Fixes required by stricter compiler used in workflows.

SQLGetInfo Workflow Fixes

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/date_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/timestamp_array_accessor.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/timestamp_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_result_set.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/flight_sql_result_set.h
cpp/src/arrow/flight/sql/odbc/odbc.def
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/calendar_utils.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/odbc_statement.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/spi/result_set.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_statement.cc
cpp/src/arrow/flight/sql/odbc/tests/odbc_test_suite.cc
cpp/src/arrow/flight/sql/odbc/tests/odbc_test_suite.h
cpp/src/arrow/flight/sql/odbc/tests/statement_test.cc

SQLFetch & SQLGetData Implementation + Tests

SQLFetch & SQLGetData Implementation

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_attr_test.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_info_test.cc

Move `#ifdef` for attributes outside of test cases

[Code Style] Move ifdefs for attributes outside of test cases

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/odbc.def
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h
cpp/src/arrow/flight/sql/odbc/tests/odbc_test_suite.h
cpp/src/arrow/flight/sql/odbc/tests/statement_test.cc

Only fetch orientation `SQL_FETCH_NEXT` is supported by the driver.

SQLFetchScroll Implementation

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/odbc.def

The purpose is to make developing against BI tools easier. 
- remove SQLErrors in this PR, as the driver manager is supposed to map SQLErrors to `SQLGetDiagRec`

Add diagnostic records for unimplemented APIs

---

cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_statement.cc
cpp/src/arrow/flight/sql/odbc/tests/statement_test.cc

Implement test cases for SQLNumResultCols

Implement tests for SQLNumResultCols

---

cpp/src/arrow/flight/sql/odbc/entry_points.cc
cpp/src/arrow/flight/sql/odbc/odbc.def
cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbc_api.h
cpp/src/arrow/flight/sql/odbc/tests/columns_test.cc
cpp/src/arrow/flight/sql/odbc/tests/tables_test.cc

Implement SQLDescribeCol

---

cpp/src/arrow/flight/sql/odbc/odbc_api.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/odbc_statement.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_descriptor.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc
cpp/src/arrow/flight/sql/odbc/tests/errors_test.cc

* Add support for allocating and freeing descriptors.
* Add tests for retrieving descriptor handle errors from driver manager, as our driver doesn't have descriptor-specific APIs implemented.

Add Descriptor support in SQLAllocHandle and SQLFreeHandle

---

cpp/src/arrow/flight/sql/odbc/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/README
cpp/src/arrow/flight/sql/odbc/install/arrow-flight-sql-odbc-patch.xml
cpp/src/arrow/flight/sql/odbc/install/arrow-flight-sql-odbc.wxs

* This PR enables the ODBC installer to register the ODBC driver on Windows, so user doesn't need to run any script to make the driver manager recognize the driver.

Register ODBC Driver on Windows 

---

cpp/src/arrow/flight/sql/odbc/performance_tests/table_read_test.py

Since the connection string says `Driver=` and not `DSN=`, it makes sense to change the command line to `driver` to indicate that we are passing the driver name value, not the DSN value

Performance test change to use driver instead of DSN

---

cpp/cmake_modules/DefineOptions.cmake
cpp/src/arrow/flight/sql/odbc/flight_sql/CMakeLists.txt
cpp/src/arrow/flight/sql/odbc/flight_sql/address_info.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/include/flight_sql/config/configuration.h
cpp/src/arrow/flight/sql/odbc/tests/columns_test.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_info_test.cc
cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc
cpp/src/arrow/flight/sql/odbc/tests/odbc_test_suite.cc
cpp/src/arrow/flight/sql/odbc/tests/statement_test.cc
cpp/src/arrow/flight/sql/odbc/tests/tables_test.cc
cpp/src/arrow/flight/sql/odbc/tests/type_info_test.cc
cpp/src/arrow/vendored/whereami/whereami.cc

- Add mac support for compiling ODBC 
- Changed compile settings to be able to build in mac 
- Added if conditional statements for windows only code 
Yes locally (currently the mac workflow is not passing due to another issue not related to this PR )
No

mac build changes

---

cpp/src/arrow/flight/sql/odbc/tests/columns_test.cc
cpp/src/arrow/flight/sql/odbc/tests/tables_test.cc
cpp/src/arrow/flight/sql/odbc/tests/type_info_test.cc

SQLDescribeCol expects `bufCharLen` to be of type `SQLSMALLINT`, so build warnings occur when `bufCharLen` is set to `SQLINTEGER`. This error did not occur on my local environment before, so I am fixing it as it occurs.

Fix build warnings treated as error

---

cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/binary_array_accessor.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/common.h
cpp/src/arrow/flight/sql/odbc/flight_sql/accessors/string_array_accessor.cc
cpp/src/arrow/flight/sql/odbc/flight_sql/get_info_cache.cc
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/attribute_utils.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/include/odbcabstraction/odbc_impl/encoding_utils.h
cpp/src/arrow/flight/sql/odbc/odbcabstraction/odbc_impl/odbc_statement.cc
cpp/src/arrow/flight/sql/odbc/tests/CMakeLists.txt

Addresses the following code review comments:
https://github.com/apache/arrow/pull/40939#discussion_r2099120394
> What does this comment mean? It seems there is a null check inside the loop. 
https://github.com/apache/arrow/pull/40939#discussion_r2099120764 
> nits, but (1) std::memcpy, (2) include cstring?
https://github.com/apache/arrow/pull/40939#discussion_r2099146199 
> nit, but is the non-const reference meant to be an in-out parameter? I think that is OK but this function confusingly uses a mix of pointers and non-const references

Address code review comments for Arrow#40939

---

cpp/src/arrow/flight/sql/odbc/tests/connection_test.cc

Assertions in this test were inconsistent with other tests.
Using `EXPECT_EQ` instead of `EXPECT_TRUE` for equality comparisons.
Yes
No

Rework assertions in connection_test

---

cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/binary_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/boolean_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/date_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/decimal_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/primitive_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/string_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/time_array_accessor_test.cc
cpp/src/arrow/flight/sql/odbc/odbc_impl/accessors/timestamp_array_accessor_test.cc

Change `flightsql-odbc` test names to follow Arrow convention and remove the underscores.
Addresses comment https://github.com/apache/arrow/pull/40939#discussion_r2099160991

Code style naming convention for `flightsql-odbc` tests
